name: ECE434_MP3_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - ipykernel=6.29.3
  - numpy=1.21.3
  - scikit-learn=1.2.1
  - matplotlib=3.4.3
  - scipy=1.7.2
  - pandas=1.4.1