name: ECE434_MP5_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - ipykernel=6.29.3
  - numpy=1.21.3
  - pandas=1.2.3
  - matplotlib=3.3.4
  - scipy=1.6.2
  - scikit-learn=1.2.1